dist: trusty
  language: node_js
  node_js:
  - stable
  branches:
    only: development
  notifications:
    email:
      recipients:
      - 1242313097@qq.com
      on_success: never
      on_failure: always
